# Berufserfahrung
<!-- NOTE: Run `biblio_full` to update the bibliography -->
## Bank of England

*Economist* (London, Vereinigtes Königreich) \hfill 2018-2020

::: {.content-hidden when-meta="cv.academic"}

- Mitinitiator und Leiter der Entwicklung eines Analysetools (R Shiny), das noch heute intern genutzt wird.
- Wirksame Mitarbeit an Kurzdossiers für Mitglieder des Monetary Policy Committee und Financial Policy Committee.
- Mitautor von Arbeitspapieren (*Staff Working Paper*) über die Zinsstrukturkurve und Nachfrage nach Zentralbankreserven.
- Präsentationen von Forschungsergebnissen sowohl intern als auch bei externen Partnern wie der Europäischen Zentralbank.

:::

*Postgraduate Intern* (London, Vereinigtes Königreich) \hfill 06/2017-08/2017

::: {.content-hidden when-meta="cv.academic"}

- Ökonometrische Analyse eines großen Paneldatensatzes in der R Programmiersprache.
- Interne Präsentation der Analyseergebnisse sowie die Erstellung eines detailierten Forschungsberichts. 

:::

::: {.content-hidden when-meta="cv.industry"}

## University of Edinburgh

*Teaching Assistant (teilzeit)* (Edinburgh, UK) \hfill 2016-2017

::: {.content-hidden when-meta="cv.academic"}

- Helped third-year econometrics students to familiarize themselves with applications of econometrics in Stata during labs.
- Actively taught econometrics in tutorials jointly with senior teaching fellow.
- Supported students in help desk sessions.

:::

::: {.content-hidden when-meta="cv.industry"}
::: {.content-hidden when-meta="cv.academic"}

## Handelsblatt Research Institute

*Third-Year Intern* (Dusseldorf, Germany) \hfill 07/2016-08/2016

- Researched economic and financial data using Bloomberg Terminal and Datastream.
- Started research on my undergraduate dissertation.

*First-Year Intern* (Dusseldorf, Germany) \hfill 06/2014-08/2014

- Data research and analysis in MS Excel for in-depth study of the experiences of German entrepreneurs trading and investing in the African market
- Used Bloomberg Terminal for daily research activities

## von Poll Immobilien GmbH

*Second-Year Intern* (Dusseldorf, German) \hfill 06/2015-07/2015

- Integrated various house price estimation models in Excel templates.
- Went to various client meetings together with colleagues and independently.

## FreshSight Ltd.

*Student Consultant (part-time)* (Edinburgh, UK) \hfill 09/2014-12/2014

- Consulted client, The Turing Trust, on how to improve its organizational management and recruitment efforts.
- Helped to create a 70 page deliverable together with a team of consultants.
- Presented results in front of client and industry experts.

:::
:::
:::

# Ausbildung

## Technische Universität Delft

*Promotion im Bereich der Vertraubaren Künstlichen Intelligenz* \hfill 2021-2026

::: {.content-hidden when-meta="cv.industry"}

- Published first-author papers on Counterfactual Explanations, Predictive Uncertainty Quantification and Mechanistic Interpretability at top-tier venues: ICML, AAAI, IEEE SaTML.
- Supervised bachelor’s and master’s theses that led to several publications as well as student software projects on related research topics.
- Frequently invited as speaker at organizations including The Alan Turing Institute, The Bank of England, De Nederlandsche Bank, Verbond van Verzekeraars.
- Founded and maintained Taija, an open-source software organization for Trustworthy Artificial Intelligence in Julia. Presented at JuliaCon Global for three consecutive years.
- Mentored first-time open-source contributors as part of Google Summer of Code and Julia Season of Contributions.

:::

## Barcelona School of Economics (BSE)

*Master Degree in Data Science*, GPA 8.67/10 \hfill 2020-2021

::: {.content-hidden when-meta="cv.industry"}

- Dissertation: Deep Vector Autoregression for Macroeconomic Data (9.5)
- Relevant modules: Machine Learning (9.0), Reinforcement Learning (10.0)

:::

*Master Degree in Economics and Finance*, GPA 9.03/10 (Jahrgangsbester) \hfill 2017-2018

::: {.content-hidden when-meta="cv.industry"}

- Dissertation: Option Pricing in the Heston Stochastic Volatility Model (10.0)
- Relevant modules: Financial Econometrics (10.0), Pricing Financial Derivatives (9.3)

:::

## The University of Edinburgh

*Master of Arts with Honours in Economics*, First Class (Preisträger) \hfill 2013-2017

::: {.content-hidden when-meta="cv.industry"}

- Dissertation: Can misguided monetary policy explain the European housing bubble? (82%)
- Honours modules: Economics of Financial Markets (86%), Adv. Mathematical Economics
(79%), Behavioural Economics (71%), Economics of Asymmetric Information (74%)

:::

# Veröffentlichungen

::: {.content-visible when-meta="cv.industry"}

Details können Sie meinem [akademischen](https://www.patalt.org/www/academic.pdf) oder [ausführlichen](https://www.patalt.org/www/full.pdf) Lebenslauf entnehmen (in englischer Sprache).

:::

::: {.content-hidden when-meta="cv.industry"}

::: {#refs-peer}
:::


# Preprints

::: {#refs-pre}
:::

# Supervision

## Master's Students

::: {#refs-mast}
:::

## Bachelor's Students

::: {#refs-bach}
:::

## Software Projects

::: {#refs-tech}
:::

# Software

::: {#refs-soft}
:::

:::

# Weitere Kompetenzen

- Sprachen: Deutsch (Muttersprache), Englisch (fließend), Spanisch (B2), Niederländisch (B2)
- Programmierung: Julia (Flux, MLJ, Zygote, ...), R, Python (PyTorch, TensorFlow, ...), git, bash, Quarto, LaTeX, (Neo-)vim

# Ausgewählte Auszeichnungen und Preise

::: {.content-hidden when-meta="cv.industry"}

- Awarded Google Summer of Code and Julia Season of Contributions grants. (2024)
- 1st Prize Winner of ING Experiment Week. (2023)
- 2nd Prize Winner of JuliaCon Pluto Notebook Competition. (2023)
- 3rd Price Winner of Novartis Datathon. (2020)
- Full-Tuition Scholarship awarded jointly by Bank of England and BSE. (2020)
- Full-Tuition Scholarship awarded BSE. (2017)
- School of Economics Joint Prize for the best performance in Economics. (2017)
- School of Economics Prize for academic excellence in Economics. (2014)

:::

::: {.content-visible when-meta="cv.industry"}

- Forschungsstipendien *Google Summer of Code* und *Julia Season of Contributions*. (2024)
- Gewinner bei der ING Experiment Week. (2023)
- Forschungsstipendium durch die Bank of England und BSE. (2020)
- School of Economics Joint Prize für herausragende akademische Leistungen im Studium. (2017)
- School of Economics Prize für herausragende akademische Leistungen im Studium. (2014)

:::

# Referenzen

Auf Anfrage erhältlich.
