---
date: last-modified
format:
  quarto-cv-pdf: default
author: Patrick Altmeyer
address: Amsterdam, North Holland, The Netherlands
# The following are optional
# phone: your contact number
email: patalt@patalt.org
github: pat-alt
orcid: 0000-0003-4726-8613
# osf: five character osf id
web: patalt.org
fontawesome: yes
bibliography: 
  peer: bib/peer.bib
  tech: bib/other.bib
  pre: bib/pre.bib
validate-yaml: false
nocite: '@*'
---

# Employment

*Bank of England*

Economist (London, UK) \hfill 2018-2020

- Co-initiated and led the development of an analysis tool that is still used internally today.
- Conducted research and analysis as co-author of staff working papers on yield curve pricing and the demand for central bank reserves.
- Policy briefing work for the Monetary Policy Committee and Financial Policy Committee involving econometric data analysis, presentations and speaking notes.

# Education

*Delft University of Technology*

Ph.D. Computer Science \hfill 2021-2025

- Published research on Counterfactual Explanations, Predictive Uncertainty Quantification and Mechanistic Interpretability in top-tier venues: ICML, AAAI, IEEE SaTML.
- Founded and maintained Taija, an open-source software organization for Trustworthy Artificial Intelligence in Julia. Presented at JuliaCon Global for three consecutive years.
- Supervised multiple bachelor’s and master’s theses as well as software projects on related research topics.

*Barcelona School of Economics (BSE)*

Master’s Degree in Data Science, GPA 8.67/10 \hfill 2020-2021

- Dissertation: Deep Vector Autoregression for Macroeconomic Data (9.5)
- Relevant modules: Machine Learning (9.0), Reinforcement Learning (10.0)

Master’s Degree in Economics and Finance, GPA 9.03/10 (top student) \hfill 2017-2018

- Dissertation: Option Pricing in the Heston Stochastic Volatility Model (10.0)
- Relevant modules: Financial Econometrics (10.0), Pricing Financial Derivatives (9.3)

*The University of Edinburgh*

Master of Arts with Honours in Economics, First Class (among top three students) \hfill 2013-2017

- Dissertation: Can misguided monetary policy explain the European housing bubble? (82%)
- Honours modules: Economics of Financial Markets (86%), Adv. Mathematical Economics
(79%), Behavioural Economics (71%), Economics of Asymmetric Information (74%)

# Skills

- Languages: German (native), English (fluent), Spanish (intermediate), Dutch (intermediate)
- Programming: Julia, R, Python, MATLAB, C++, SQL, git, Bash, Quarto, LaTeX

# Selected Awards & Honours

- 2nd Prize Winner of JuliaCon Pluto Notebook Competition. (2023)
- 1st Prize Winner of ING Experiment Week. (2023)
- Full scholarship for master’s in data science awarded jointly by Bank of England and BSE. (2020)
- Full scholarship for master’s in economics and finance awarded BSE. (2017)
- Edinburgh University School of Economics Joint Prize for the best performance in Economics. (2017)
- School of Economics Prize for academic excellence in Economics. (2014)

# Publications

::: {#refs-peer}
:::

# Technical Reports

::: {#refs-tech}
:::

# Preprints

::: {#refs-pre}
:::

# References

Available upon request.
