# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#hero'
    weight: 10
  - name: Work and Outreach
    url: /work/
    weight: 20
  - name: About me
    url: /about/
    weight: 30
  - name: Code
    identifier: code
    weight: 40
  - name: AlgorithmicRecourse.jl
    url: https://www.paltmeyer.com/AlgorithmicRecourse.jl/dev/
    weight: 10
    parent: code
  - name: BayesLaplace.jl
    url: https://www.paltmeyer.com/BayesLaplace.jl/dev/ 
    weight: 20
    parent: code
  - name: Other
    identifier: other
    weight: 50
  - name: Trustworthy AI
    url: https://www.paltmeyer.com/tai/
    weight: 10
    parent: other
  
