::: {.column-screen}

::: {.hero-banner}

::: {.hero-banner-carousel}
{{< include content/news/news.qmd >}}
:::

::: {.hero-banner-text}
# News

- On May 7-8, I'll be presenting some of my PhD research at the [DSCNext Conference Europe 2025](https://dscnextcon.com/speaker/patrick/).
- Taija, the organization that hosts software geared towards Trustworthy Artificial Intelligence in Julia, has its own website now: [www.taija.org](https://www.taija.org/). The ecosystem keeps slowly growing. If you're interested in contributing, please get in touch!
- In July 2024, I presented our position paper "Stop Making Unscientific AGI Performance Claims" at ICML 2024. We argue that finding patterns in latent embeddings of models like LLMs is not surprising and call for the academic community to exercise extra caution when interpreting such findings. [[preprint](https://arxiv.org/abs/2402.03962)], [[blog post](/blog/posts/spurious-sparks/index.qmd)], [[slides/poster](/content/talks/posts/2024-icml/index.qmd)]
- In May 2024, I was in London to present research at [ECONDAT 2024](/content/talks/posts/2024-econdat/) (King's College London), [The Alan Turing Institute](/content/talks/posts/2024-turing/) and [Imperial College London](/content/talks/posts/2024-imperial/). 
- In Frebruary 2024, I attended [AAAI 2024](https://aaai.org/aaai-conference/) in Vancouver, Canada presenting our work on *Faithful Model Explanations through Energy-Constrained Conformal Counterfactuals*. If you're around, come say hi! [[preprint](https://arxiv.org/abs/2312.10648)], [[blog](/blog/posts/eccco/index.qmd)], [[TDS](https://medium.com/towards-data-science/ecccos-from-the-black-box-c4bd6ef20263)], [[code](https://github.com/pat-alt/ECCCo.jl)], [[slides/poster](/content/talks/posts/2024-aaai/index.qmd)]

:::

::: 

:::

