---
title: "Counterfactual Training: Teaching Models Plausible and Actionable Explanations"
date: '2026-03-23'
venue: IEEE Conference on Secure and Trustworthy Machine Learning
categories:
  - counterfactual explanations
  - contrastive divergence
  - adversarial machine learning
  - representation learning
description: >-
  Counterfactual training leverages counterfactual explanations to make models more 1) explainable, 2) sensitive to actionability constraints and 3) adversarially robust.
---

## Abstract

 We propose a novel training regime termed counterfactual training that leverages counterfactual explanations to increase the explanatory capacity of models. Counterfactual explanations have emerged as a popular post-hoc explanation method for opaque machine learning models: they inform how factual inputs would need to change in order for a model to produce some desired output. To be useful in real-world decision-making systems, counterfactuals should be plausible with respect to the underlying data and actionable with respect to the feature mutability constraints. Much existing research has therefore focused on developing post-hoc methods to generate counterfactuals that meet these desiderata. In this work, we instead hold models directly accountable for the desired end goal: counterfactual training employs counterfactuals during the training phase to minimize the divergence between learned representations and plausible, actionable explanations. We demonstrate empirically and theoretically that our proposed method facilitates training models that deliver inherently desirable counterfactual explanations and additionally exhibit improved adversarial robustness.

**Full paper**: please find all available versions [here](https://scholar.google.com/scholar?oi=bibs&hl=en&cluster=229746294335801966).

