---
title: "Betrouwbare Kunstmatige Intelligentie"
subtitle: Een korte presentatie over mijn onderzoek
author: 
  - name: "Patrick Altmeyer"
    url: https://www.paltmeyer.com/
institute: Delft University of Technology
date: today
format: 
  tudelft-revealjs:
    theme: custom.scss
    self-contained: true
    smaller: false
    scrollable: true
    preview-links: auto
    slide-number: true
    transition: slide
    background-transition: fade
    fig-align: center
    html-math-method: mathjax
    include-in-header:
      - text: |
          <script>
          MathJax = {
            options: {
              menuOptions: {
                settings: {
                  assistiveMml: false
                }
              }
            }
          };
          </script>
revealjs-plugins:
  - pointer
crossref: 
  prp-title: RQ
  prp-prefix: RQ
bibliography: ../../../../bib.bib
---

## What is Kunstmatige Intelligentie?

::: {.notes}
- In de tijden van ChatGPT heeft iederen een idee van KI maar het is niet heel klar wat het eigenlijk betekent. 
- Volgens mij bedoelen mensen meestal "machine learning" als ze 'KI' zeggen.
- "Machine learning", of koort "ML", is niet hetzelfde als "KI" maar het is wel een belangrijk onderdeel van KI.
- "ML" is een manier om een computer te trainen om een taak te doen zonder dat je de computer precies vertelt hoe hij het moet doen.
- Je geeft de computer aleen een objectief en een hoop voorbeelden. Dan lat je de computer zelf een manier vinden om het objectief te bereiken en ten slotte hoop je dat de computer goed geleerd heeft.
:::

## "Diep Leren" - de huidige standaard

::: {.notes}

- De kerntechniek van de sterkste KI systemen van vandaag is "diep leren", of "deep learning" in het Engels.
- In het kort, bij diep leren gebruiken we grote modellen met veel instellingen. Deze waarden worden geleerd en verbeterd via optimalisatie.
- OpenAI's ChatGPT heeft zoveel succes gehad omdat het een heel groot model is. Eigenlijk is het officiële motto van OpenA: "Scale is all you need", dus "Schaal is alles wat je nodig hebt".

:::

## Klinkt goed, maar ...

::: {.notes}

- Een van de grootste problemen met diep leren is dat de modellen zo groot zijn dat niemand ze echt begrijpt.
- Je kan niet makkelijk het model openen en zien hoe het werkt.
- Het model is een black box.
- Dit is heel problematisch voor de betrouwbaarheid van KI systemen, vooral als ze gebruikt worden in kritische toepassingen zoals medische diagnoses of autonome voertuigen.
- Maar ook en mer aldagelijkse toepassingen: heeft iemand hier eermaal een lening aangevraagd? Of een sollicitatie gedaan? Of een verzekering afgesloten? Dan is de kans groot dat een KI systeem een rol heeft gespeld in de beslissing.

:::

## Betrouwbaarheid door Verklaarbaarheid

::: {.notes}

- Een van de belangrijkste manieren om de betrouwbaarheid van KI systemen te verbeteren is door ze verklaarbaar te maken.
- Dit is de focus van mijn onderzoek.
- Ik richt mij in het bijzonder op een methode die "counterfactual explanations" heet.
- Intuïtief vragen we wat we moeten veranderen aan de modelinputs om de outputs te veranderen.
- Bijvorbeeld zien jullie hier en model dat tussen katjes and hondjes kan onderscheiden.
- Om te begrijpen waarom het model een katje ziet, kunnen we de characteristieken van het katje veranderen en kijken hoe het model reageert.
- Hier zie je how het katje van links oven naar rechts beneden wandelt.
- Dit betekent in dit geval dat het katje zijn staartje moet inkorten en iets groter moet worden.

:::