---
title: Welcome
author: Patrick Altmeyer
date: '2021-02-01'
description: >-
  The obligatory welcome post and a shout-out to Yihui Xie and the folks behind quarto.
---

Welcome to my blog! 

Having worked with R Markdown and some of [Yihui Xie](https://yihui.org/)'s amazing packages for years, I have only now come across his [blogdown](https://bookdown.org/yihui/blogdown/) package. For a while I have been thinking about a good way to share some of my work and actually started collecting snippets in a [Gitbook](https://pat-alt.github.io/fromScratch/) through [bookdown](https://bookdown.org/yihui/bookdown/) quite some time ago. While the book is a work-in-progress that I aim to finish eventually, I will use this website to regularly share content related to my work, research and other things. 

:::{.callout-note}

**Update on Feb 20, 2022**

I have recently migrated this blog and pretty much everything else I do to [quarto](https://quarto.org/). 

> Quarto® is an open-source scientific and technical publishing system built on Pandoc.

Based on my first few experiences I would go further and say that quarto is *the only* open-source scientific and technical publishing system you'll ever need. The project is supported by RStudio and (unsurprisingly) Yihui Xie is one of the contributors. Go check it out!
:::




