### Biography

> My current research revolves around **Counterfactual Explanations** and **Probabilistic Machine Learning**. Previously, I worked as an Economist for the Bank of England.

**Researching Trustworthy Artificial Intelligence (AI) for Finance and Economics**. I am an economist by background with an interest in cross-disciplinary research on the intersection of Trustworthy AI and Financial Economics. For my PhD in Trustworthy AI, I currently focus on Counterfactual Explanations and Probabilisitic Machine Learning under supervision of [Cynthia Liem](https://www.cynthialiem.com){target="_blank"} and [Arie van Deursen](https://avandeursen.com/){target="_blank"} at [Delft University of Technology](https://tudelft.nl/){target="_blank"}. I am also a member of the [AI for Fintech Research Lab](https://se.ewi.tudelft.nl/ai4fintech/index.html){target="_blank"}.

Previously, I worked as an economist for [Bank of England](https://www.bankofengland.co.uk){target="_blank"} where I was involved in research, monetary policy briefings and market intelligence. I hold two masters degrees from [Barcelona School of Economics](https://bse.eu){target="_blank"}, one in [Data Science](https://bse.eu/study/masters-programs/data-science-methodology){target="_blank"} and one in [Finance](https://bse.eu/study/masters-programs/finance){target="_blank"}. I also hold an undergraduate degree in Economics from the [University of Edinburgh](https://www.ed.ac.uk){target="_blank"}. 

I primarily code in [Julia](https://github.com/JuliaLang/julia){target="_blank"} and publish through [Quarto](https://github.com/quarto-dev){target="_blank"}. Occasionally I also use R, Python and C++. As much as possible I contribute to **open-source**: [Github](https://github.com/pat-alt){target="_blank"}.

📄 **Resume**: [[detailed](/www/resume_long.pdf){target="_blank"}, [compact](/www/resume.pdf){target="_blank"}]
