---
title: "Patrick Altmeyer's resume"
output:
    pagedown::html_resume:
        self_contained: true
knit: pagedown::chrome_print
suppress-bibliography: true
bibliography: https://raw.githubusercontent.com/pat-alt/bib/main/bib.bib
---

```{css, echo=FALSE}
.pagedjs_page:not(:first-of-type) {
  --sidebar-width: 0rem;
  --sidebar-background-color: #ffffff;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.2in;
}
```

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> p.altmeyer@tudelft.nl
- <i class="fa fa-home"></i> [www.patalt.org](https://www.patalt.org/)
- <i class="fa fa-github"></i> [github.com/pat-alt](https://github.com/pat-alt)
- <i class="fa fa-phone"></i> +49 176 48726927
- For more information, please contact me via email.


Skills {#skills}
--------------------------------------------------------------------------------

- Experienced in Machine Learning, Finance, Economics and Monetary Policy.

- Highly skilled in Julia, R, Python and Quarto.

- Research expertise in the field of Explainable Artificial Intelligence.


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

<!-- This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown). -->

Last updated on `r Sys.Date()`.



Main
================================================================================

Patrick Altmeyer {#title}
--------------------------------------------------------------------------------

### Researching Trustworthy Artificial Intelligence (AI) for Finance and Economics

I am an economist by background with an interest in cross-disciplinary research on the intersection of Trustworthy AI and Financial Economics. For my PhD in Trustworthy AI, I currently focus on Counterfactual Explanations and Probabilisitic Machine Learning under supervision of [Cynthia Liem](https://www.cynthialiem.com) and [Arie van Deursen](https://avandeursen.com/) at [Delft University of Technology](https://tudelft.nl/).


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### PhD in Computer Science 

Delft University of Technology

Delft, Netherlands

2025 - 2021

Thesis topic: Counterfactual Reasoning and Probabilistic Methods for Trustworthy AI with Applications in Finance

### Master in Data Science

Barcelona School of Economics

Barcelona, Spain

2021

Thesis: Deep Vector Autoregression for Macroeconomic Data

### Master in Economics and Finance

Barcelona School of Economics

Barcelona, Spain

2018

Thesis: Option Pricing in the Heston Stochastic Volatility Model

### Master of Arts with Honours in Economics

University of Edinburgh

Edinburgh, United Kingdom

2017

Thesis: Can misguided monetary policy explain the European housing bubble?
  
Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Economist

Bank of England

London, United Kingdom

2021 - 2018

::: concise
- Co-author of two staff working papers.
- Econometric data analysis.
- Co-initiated and led app development.
- Briefing work for policy committees.
:::

### Postgraduate Intern

Bank of England

London, United Kingdom

2017

::: concise
- Econometric analysis of transaction data set in R.
- Internal presentation of project results.
:::

Teaching and Supervision {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Google Summer of Code

[Project](https://summerofcode.withgoogle.com/programs/2024/projects/fkvFPluF) Mentor of the Google Summer of Code program

Virtual

2024

### Julia Season of Contributions

[Project](https://www.taija.org/blog/posts/causal-recourse/) Mentor of Julia Season of Contributions program

Virtual

2024

### Master's Thesis Supervision

Research co-supervisor of various master's students

Delft, Netherlands

2024 - 2023

### Software Project Supervision

Project supervisor for three groups of students

Delft, Netherlands

2024 - 2023

::: concise
- Proposal of two software projects related to Trustworthy AI in Julia.
- Supervision of two groups of five undergraduate students working on the project.
:::

### Bachelor's Thesis Supervision

Research supervisor for group of students

Delft, Netherlands

2022

::: concise
- Proposal of final-year research project on Endogenous Dynamics in Algorithmic Recourse.
- Supervision of group of three undergraduate students working on the project.
:::

### Foundations of Data Science Summer School

Teaching Assistant at Barcelona School of Economics

Barcelona, Spain

2021

### Introduction course to R and Git

Lead Trainer at Analytics Enablement Hub, Bank of England.

London, United Kingdom

2020 - 2019

### Honours Modules in Econometrics

Teaching assistant at School of Economics, University of Edinburgh

Edinburgh, United Kingdom

2017 - 2016


Selected Publications {data-icon=file}
--------------------------------------------------------------------------------

### Position: Stop Making Unscientific AGI Performance Claims

Proceedings of the 41st International Conference on Machine Learning: [[PDF](https://proceedings.mlr.press/v235/altmeyer24a.html), [code](https://github.com/pat-alt/spurious_sentience)]

Vienna, Austria

2024

**Altmeyer P.**, Demetriou A.M., Bartlett A., Liem C.C.S.

### Faithful Model Explanations through Energy-Constrained Conformal Counterfactuals

The 38th Annual AAAI Conference on Artificial Intelligence: [[PDF](https://ojs.aaai.org/index.php/AAAI/article/view/28956), [code](https://github.com/pat-alt/ECCCo.jl)]

Vancouver, Canada

2024

**Altmeyer P.**, Farmanbar M., van Deursen A., Liem C.C.S.

### Explaining Black-Box Model through Counterfactuals

The Proceedings of the JuliaCon Conferences: [[PDF](https://proceedings.juliacon.org/papers/10.21105/jcon.00130)]

Delft, Netherlands

2023

**Altmeyer P.**, van Deursen A., Liem C.C.S.

### Endogenous Macrodynamics in Algorithmic Recourse

First IEEE Conference on Secure and Trustworthy Machine Learning: [[PDF](https://openreview.net/forum?id=-LFT2YicI9v), [code](https://github.com/pat-alt/endogenous-macrodynamics-in-algorithmic-recourse)]

Raleigh, North Carolina, United States

2023

**Altmeyer P.**, Angela G., Buszydlik A., Dobiczek K., van Deursen A., Liem C.C.S.

### Yield Curve Sensitivity to Investor Positioning Around Economic Shocks

Bank of England Staff Working Paper: [[PDF](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4506611)]

London, United Kingdom

2023

**Altmeyer P.**, Boneva L., Kinston R., Saha S., Stoja E.

### Deep Vector Autoregression for Macroeconomic Data 

Masters Thesis (selected for publication): [[PDF](https://repositori.upf.edu/bitstream/handle/10230/49204/TFM2021BGSEAgustiDeep.pdf?sequence=1&isAllowed=y)], [[GitHub](https://github.com/pat-alt/deepvarsMacro)]

Barcelona, Spain

2021

Agustí M., **Altmeyer P.**, Vidal-Quadras Costa I.

### Option Pricing in the Heston Stochastic Volatility Model: an Empirical Evaluation

Masters Thesis (selected for publication): [[PDF](https://repositori.upf.edu/handle/10230/35862)]

Barcelona, Spain

2018

**Altmeyer P.**, Grapendal J., Pravosud M., Quintana G.

Selected Conferences, Workshops and Posters {data-icon=comments}
--------------------------------------------------------------------------------

### JuliaCon 2024

Multiple [talks](https://pretalx.com/juliacon2024/me/submissions/) about Taija, Quarto and more.

Eindhoven, Netherlands

2024

### Trustworthy AI in Julia

[Invited talk](https://www.patalt.org/content/talks/posts/2024-turing/) at the Alan Turing Institute on Trustworthy AI in Julia.

London, United Kingdom

2024

### XAI seminar @ Imperial College London

[Presented](https://www.patalt.org/content/talks/posts/2024-imperial/) our AAAI 2024 paper at an XAI seminar at Imperial College London.

London, United Kingdom

2024

### ECONDAT 2024

Presented *Against Spurious Sparks – Dovelating Inflated AI Claims* at [ECONDAT 2024](https://www.kcl.ac.uk/events/econdat-conference-2024) conference.

London, United Kingdom

2024

### Navigating the Interplay of Explainability and Privacy in AI

[Contributed talk](https://www.paltmeyer.com/content/talks/posts/2024-aaai/) at [workshop](https://www.tudelft.nl/evenementen/2024/delft-ai/workshop-navigating-the-interplay-of-explainability-and-privacy-in-ai): Faithful Model Explanations through Energy-Constrained Conformal Counterfactuals

Delft, Netherlands

2024

### Workshop at De Nederlandsche Bank

[Invited talk](https://www.paltmeyer.com/content/talks/posts/2023-dnb/): Faithful Model Explanations-Central Bank Supervision in the Age of AI

Amsterdam, Netherlands

2023

### Datamiddag 2023: van PET tot Haring

[Invited talk](https://www.paltmeyer.com/content/talks/posts/2023-insurance-academy/): Faithful Model Explanations

The Hague, Netherlands

2023

### JuliaCon 2023

[Main talk](https://www.paltmeyer.com/content/talks/posts/2023-juliacon/): Predictive Uncertainty Quantification in Machine Learning

MIT in Boston, USA

2023

### Delft FinTech Lab Launch

[Invited talk](https://www.paltmeyer.com/content/talks/posts/2023-delft-fintech/): Echos from the Black Box

Delft, Netherlands

2023

### First IEEE Conference on Secure and Trustworthy Machine Learning

[Oral](https://www.paltmeyer.com/content/talks/posts/2023-ieee-satml/): Endogenous Macrodynamics in Algorithmic Recourse

Raleigh, North Carolina

2023

### New Methods Seminar at the Bank of England

[Invited talk](https://www.paltmeyer.com/content/talks/posts/2022-boe/): Explaining Black-Box Models through Counterfactuals

London, United Kingdom

2022

### ING Data Science Community Conference 2022

[Contributed talk](https://www.paltmeyer.com/content/talks/posts/2022-dscc/): Explaining Black-Box Models through Counterfactuals

Amsterdam, Netherlands

2022

### JuliaCon 2022

Presented Julia packages I developed

Virtual

2022

::: concise
- [Explaining Black-Box Models through Counterfactuals](https://pretalx.com/juliacon-2022/talk/HU8FVH/) (main talk)
- [Effortless Bayesian Deep Learning through Laplace Redux](https://pretalx.com/juliacon-2022/talk/Z7MXFS/) (lightening talk)
- [Julia and Quarto: A Match Made in Heaven?](https://www.youtube.com/watch?v=9L5Oy3oGoTU) (experience talk)
:::

### ProbAI 2022 Summer School

Poster presentation "Explainable AI: Probabilistic Methods for Counterfactual Explanations": [[poster](https://github.com/juliatrustworthyai/CounterfactualExplanations.jl/blob/main/dev/resources/probai/poster.pdf)]

Helsinki, Finland

2022

### TU Delft EEMCS PhD event

Poster presentation "Counterfactual Explanations and Algorithmic Recourse": [[poster](https://miro.com/app/board/uXjVOF7o3AA=/?moveToWidget=3458764520940310671&cot=14)]

Delft, Netherlands

2022

### De Nederlandse Bank Conference "Central Bankers Go Data Driven: Applications of AI and ML for Policy and Prudential Supervision"

Poster presentation of @altmeyer2021deep.

Amsterdam, Netherlands

2022

### IFC and Bank of Italy workshop on "Data science in central banking"

Presentation of @altmeyer2021deep: [[event link](https://www.bis.org/ifc/events/220214_ifc.htm)], [[YouTube](https://youtu.be/5-TNJtICw7E?t=4567)]

Virtual

2022

### NeurIPS 2021 MLECON Workshop

Poster presentation of @altmeyer2021deep: [[event link](https://nips.cc/Conferences/2021/ScheduleMultitrack?event=21847)]

Virtual

2021

### IFABS 2021 Oxford

Presented our upcoming BoE Staff Working Paper on yield curve pricing [[event link](https://www.ifabs.org/copy-of-ifabs-oxford-call-1)]

Virtual

2021

### Money markets and Central Bank Balance Sheets

Presented research on demand for central bank reserves at ECB: [[event link](https://www.ecb.europa.eu/pub/conferences/html/20191111_ecb_money_market_workshop_conference.en.html)]

Frankfurt, Germany

2019

Selected Open-Source Software {data-icon=code} 
--------------------------------------------------------------------------------

### `ConformalPrediction.jl`

Julia package for Conformal Prediction: [[docs](https://www.paltmeyer.com/ConformalPrediction.jl/stable/)], [[GitHub](https://github.com/juliatrustworthyai/ConformalPrediction.jl)]

N/A

2022-2024

### `CounterfactualExplanations.jl`

Julia package for Counterfactual Explanations: [[docs](https://www.paltmeyer.com/CounterfactualExplanations.jl/stable/)], [[GitHub](https://github.com/juliatrustworthyai/CounterfactualExplanations.jl)]

N/A

2021-2024

### `LaplaceRedux.jl`

Julia package for effortless Bayesian Deep Learning: [[docs](https://www.paltmeyer.com/LaplaceRedux.jl/stable/)], [[GitHub](https://github.com/juliatrustworthyai/LaplaceRedux.jl)]

N/A

2021-2024

### `deepvars`

R package implementing Deep Vector Autoregression [@altmeyer2021deep]: [[GitHub](https://github.com/pat-alt/deepvars)]

N/A

2021-2022

Outreach and Volunteering {data-icon=handshake}
--------------------------------------------------------------------------------

### Personal blog

Communication AI in an accessible, visual manner: [[url](https://www.paltmeyer.com/blog/)]

N/A

2022 - 2021

### Class representative

Masters in Data Science

Barcelona, Spain

2020

### TEDx talk

Held a TEDx talk about European Integration: [[YouTube](https://www.youtube.com/watch?v=b8qpLOMGYT0)]

Edinburgh, United Kingdom

2016


Scholarships and awards {data-icon=award}
--------------------------------------------------------------------------------

### [Pluto Notebook Competition for JuliaCon2023](https://info.juliahub.com/pluto-notebook-winner-23)

2nd Price Winner

MIT in Boston, USA

2023

### Novartis Datathon

3rd Price Winner of Datathon

Barcelona, Spain

2020

### Fee Waiver and Funding for Masters 

Full funding for Masters in Data Science through BSE and Bank of England

Barcelona, Spain

2020

### Fee waiver for Masters

Total tuition fee waiver for Master in Finance through BSE

Barcelona, Spain

2017

### School of Economics Prize

Edinburgh University School of Economics Joint Prize for the best performance in Economics

Edinburgh, United Kingdom

2017

### School of Economics Prize

School of Economics Prize for academic excellence in Economics

Edinburgh, United Kingdom

2015
