---
title: "Patrick Altmeyer's resume"
output:
    pagedown::html_resume:
        self_contained: true
knit: pagedown::chrome_print
suppress-bibliography: true
bibliography: https://raw.githubusercontent.com/pat-alt/bib/main/bib.bib
---

```{css, echo=FALSE}
.pagedjs_page:not(:first-of-type) {
  --sidebar-width: 0rem;
  --sidebar-background-color: #ffffff;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.2in;
}
```

Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-envelope"></i> p.altmeyer@tudelft.nl
- <i class="fa fa-home"></i> [www.paltmeyer.com](https://www.paltmeyer.com/)
- <i class="fa fa-github"></i> [github.com/pat-alt](https://github.com/pat-alt)
- <i class="fa fa-phone"></i> +49 176 48726927
- For more information, please contact me via email.


Skills {#skills}
--------------------------------------------------------------------------------

- Experienced in Machine Learning, Finance, Economics and Monetary Policy.

- Highly skilled in Julia, R, Python and Markdown.

- Solid knowledge of C++ (Rcpp), SQL, MATLAB, Stata, HTML, CSS, git, docker, AWS and LaTeX.


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

<!-- This resume was made with the R package [**pagedown**](https://github.com/rstudio/pagedown). -->

Last updated on `r Sys.Date()`.



Main
================================================================================

Patrick Altmeyer {#title}
--------------------------------------------------------------------------------

### Researching Trustworthy Artificial Intelligence (AI) for Finance and Economics

I am an economist by background with an interest in cross-disciplinary research on the intersection of Trustworthy AI and Financial Economics. For my PhD in Trustworthy AI, I currently focus on Counterfactual Explanations and Probabilisitic Machine Learning under supervision of [Cynthia Liem](https://www.cynthialiem.com) at [Delft University of Technology](https://tudelft.nl/).


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### PhD in Computer Science 

Delft University of Technology

Delft, Netherlands

2025 - 2021

Thesis topic: Trustworthy Artificial Intelligence

### Master in Data Science

Barcelona School of Economics

Barcelona, Spain

2021

Thesis: Deep Vector Autoregression for Macroeconomic Data

### Master in Finance

Barcelona School of Economics

Barcelona, Spain

2018

Thesis: Option Pricing in the Heston Stochastic Volatility Model

### Master of Arts with Honours in Economics

University of Edinburgh

Edinburgh, United Kingdom

2017

Thesis: Can misguided monetary policy explain the European housing bubble?
  
Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Economist

Bank of England

London, United Kingdom

2021 - 2018

::: concise
- Co-author of two staff working papers (upcoming).
- Co-initiated and led app development.
- Briefing work for policy committees.
:::

### Postgraduate Intern

Bank of England

London, United Kingdom

2017

::: concise
- Econometric analysis of transaction data set in R.
- Internal presentation of project results.
:::

Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

### Research project

Research supervisor for group of students

Delft, Netherlands

2022

::: concise
- Proposal of final-year research project on Endogenous Dynamics in Algorithmic Recourse.
- Supervision of group of three undergraduate students working on the project.
:::

### Foundations of Data Science Summer School

Teaching Assistant at Barcelona School of Economics

Barcelona, Spain

2021

### Introduction course to R and Git

Lead Trainer at Analytics Enablement Hub, Bank of England.

London, United Kingdom

2020 - 2019

### Honours Modules in Econometrics

Teaching assistant at School of Economics, University of Edinburgh

Edinburgh, United Kingdom

2017 - 2016


Selected Publications and Posters {data-icon=file}
--------------------------------------------------------------------------------

### Yield Curve Sensitivity to Investor Positioning Around Economic Shocks

Bank of England Staff Working Paper (upcoming)

London, United Kingdom

2022

**Altmeyer P.**, Boneva L., Kinston R., Saha S., Stoja E.

### Deep Vector Autoregression for Macroeconomic Data 

Masters Thesis (selected for publication): [[PDF](https://repositori.upf.edu/bitstream/handle/10230/49204/TFM2021BGSEAgustiDeep.pdf?sequence=1&isAllowed=y)], [[GitHub](https://github.com/pat-alt/deepvarsMacro)]

Barcelona, Spain

2021

Agustí M., **Altmeyer P.**, Vidal-Quadras Costa I.

### Option Pricing in the Heston Stochastic Volatility Model: an Empirical Evaluation

Masters Thesis (selected for publication): [[PDF](https://repositori.upf.edu/handle/10230/35862)]

Barcelona, Spain

2018

**Altmeyer P.**, Grapendal J., Pravosud M., Quintana G.

Conferences and Workshops {data-icon=comments}
--------------------------------------------------------------------------------

### IFC and Bank of Italy workshop on "Data science in central banking"

Presentation of @altmeyer2021deep: [[url](https://www.bis.org/ifc/events/220214_ifc.htm)], [[YouTube](https://youtu.be/5-TNJtICw7E?t=4567)]

Virtual

2022

### NeurIPS 2021 MLECON Workshop

Poster presentation of @altmeyer2021deep: [[url](https://nips.cc/Conferences/2021/ScheduleMultitrack?event=21847)]

Virtual

2021

### IFABS 2021 Oxford

Presented our BoE Staff Working Paper on yield curve pricing

Virtual

2021

### Money markets and Central Bank Balance Sheets

Presented research on demand for central bank reserves at ECB: [[url](https://www.ecb.europa.eu/pub/conferences/html/20191111_ecb_money_market_workshop_conference.en.html)]

Frankfurt, Germany

2019

Selected Open-Source Software {data-icon=code} 
--------------------------------------------------------------------------------

### `CounterfactualExplanations.jl`

Julia package for Counterfactual Explanations: [[stable docs](https://www.paltmeyer.com/CounterfactualExplanations.jl/stable/)], [[GitHub](https://github.com/pat-alt/CounterfactualExplanations.jl)]

N/A

2021-2022

### `BayesLaplace.jl`

Pure-play Julia package for effortless Bayesian Deep Learning: [[dev docs](https://www.paltmeyer.com/BayesLaplace.jl/dev/)], [[GitHub](https://github.com/pat-alt/BayesLaplace.jl)]

N/A

2021-2022

### `deepvars`

R package implementing Deep Vector Autoregression [@altmeyer2021deep]: [[GitHub](https://github.com/pat-alt/deepvars)]

N/A

2021-2022

Outreach and Volunteering {data-icon=handshake}
--------------------------------------------------------------------------------

### Personal blog

Presenting AI in an accessible manner: [[url](https://www.paltmeyer.com/blog/)]

N/A

2022 - 2021

### Class representative

Masters in Data Science

Barcelona, Spain

2020

### TEDx talk

Held a TEDx talk about European Integration: [[YouTube](https://www.youtube.com/watch?v=b8qpLOMGYT0)]

Edinburgh, United Kingdom

2016


Scholarships and awards {data-icon=award}
--------------------------------------------------------------------------------

### Novartis Datathon

3rd Price Winner of Datathon

Barcelona, Spain

2020

### Fee Waiver and Funding for Masters 

Full funding for Masters in Data Science through BSE and Bank of England

Barcelona, Spain

2020

### Fee waiver for Masters

Total tuition fee waiver for Master in Finance through BSE

Barcelona, Spain

2017

### School of Economics Prize

Edinburgh University School of Economics Joint Prize for the best performance in Economics

Edinburgh, United Kingdom

2017

### School of Economics Prize

School of Economics Prize for academic excellence in Economics

Edinburgh, United Kingdom

2015
